### ISSUE TITLE
Display a custom message when add to cart is clicked

### ISSUE THREAD

**Issue by IsaacAvoseh** [notrab/react-use-cart#100]
Please, how do I display a custom message with toastify or sweetalert when adding to cart( addItem ) ?

**Comment by notrab** [comment]
Hey @IsaacAvoseh 

Inside of the `<CartProvider />` you can pass it a function to `onItemAdd`/`onItemUpdate`/`onItemRemove` etc.

See this example:

https://github.com/GraphCMS/gatsby-graphcms-ecommerce-starter/blob/master/gatsby-browser.js#L46-L48
]
https://github.com/GraphCMS/gatsby-graphcms-ecommerce-starter/blob/master/src/utils/cart-helpers.js#L1-L8

**Comment by IsaacAvoseh** [comment]
Great, so helpful, thanks a million.
