### ISSUE TITLE
TypeError: addItem is not a function

### ISSUE THREAD

**Issue by brixNessia** [notrab/react-use-cart#102]
AddItem is working at first, but when I refresh the page this AddItem is not a function error is displayed. I've tried console.log() the value of useCart and all the function is gone when I refresh it.

**Comment by notrab** [comment]
Hello

please provide some kind of codesandbox showing the error so I can help further. 

Thanks 🙏

**Comment by brixNessia** [comment]
This is the value if the useCart() that holds the addItem function when I don't refresh the page. 
![useCartWorking](https://user-images.githubusercontent.com/33595897/156118188-bd538a67-3de0-4a6d-a943-2bc02b3028c9.png)

This is the value if the useCart() that holds the addItem function when I refresh the page. 
![useCartNotWorking](https://user-images.githubusercontent.com/33595897/156118281-89b663c4-1462-418e-bfa6-ccfcf40fc59e.png)

This is the error when I try to addItems in the cart
![Error](https://user-images.githubusercontent.com/33595897/156118347-9e89cd43-50b1-4685-9ecf-7fe45bdcb5a2.png)

@notrab

**Comment by brixNessia** [comment]
This is the function that handles the addItem to cart
![image](https://user-images.githubusercontent.com/33595897/156118474-f185fcef-1fe4-46cd-9702-ec065c16da56.png)

**Comment by notrab** [comment]
> please provide some kind of codesandbox showing the error so I can help further.

**Comment by Sudharsan-learning** [comment]
Here the code sandbox link 

https://codesandbox.io/s/modest-sid-gkvyp1?file=/src/App.js

I have been provided the same code in npm package Demo code and it shows the same error.
Please help us!!

**Comment by Sudharsan-learning** [comment]
@notrab  Thank you for your response.

I already found it.
