### ISSUE TITLE
Uncaught TypeError: addItem is not a function IONIC REACT

### ISSUE THREAD

**Issue by r00t3rsec** [notrab/react-use-cart#109]
I get this error when i click button add to cart  : Uncaught TypeError: addItem is not a function
I import collection 
```
import React, { useState } from 'react';
import { useCart } from "react-use-cart";
 const { addItem } = useCart();
```
And call function like this: 
```
<IonNote slot="end"><IonButton onClick={() => addItem(item, 1)}>Добави</IonButton></IonNote>
```

**Comment by notrab** [comment]
Hey

Have you wrapped the app in the provider? If so, please provide a full code example showing the error so it can be replicated my end.

Thanks 🙌🏻

**Comment by r00t3rsec** [comment]
Fixed , and yea if someone use IONIC and REACT and get this error , just go to App.tsx and add <CartProvider> beforce  <IonApp> and closetag after </IonApp>
