### ISSUE TITLE
emptyCart() navigate the user to cart page

### ISSUE THREAD

**Issue by hazem-saeed** [notrab/react-use-cart#123]
I'm using the package in my next.js project. When the user clicks the send button to complete their purchase, I added emptyCart() after the order is creation success. But emptyCart() navigates the user to the cart page!

I checked the function, but I found nothing of that behavior in the package.

Can you please check it out, and tell me how to override this?

Thanks

**Comment by notrab** [comment]
Hey @hazem-saeed 

This has to be something specific to your code base. There's nothing in the package that does any routing.
