### ISSUE TITLE
Request to Release New Version Including Latest Commits

### ISSUE THREAD

**Issue by Nico-Gia** [notrab/react-use-cart#137]
Hello, I noticed that the latest commits are not included in the latest version (1.13.0). Would you mind releasing a new version to incorporate these updates? Thank you!

**Comment by notrab** [comment]
Hey @Nico-Gia! Sorry about that, I just realised the previous commits failed to run due to an outdated ubuntu image.

The latest changes should be live now https://github.com/notrab/react-use-cart/releases/tag/v1.14.0

**Comment by Nico-Gia** [comment]
Great, thanks for the quick intervention!
