### ISSUE TITLE
Add Gatsby example

### ISSUE THREAD

**Issue by notrab** [notrab/react-use-cart#34]
We should add a Gatsby example that shows how to wrap Gatsby with `CartProvider` and make a few function calls.

**Comment by spences10** [comment]
Just landed here from scrolling through all the open issues for Hacktoberfest @notrab! 😁

What does the example need to be? 

I'm guessing the `CartProvider` needs to be high up in the component tree to be available to the rest of the project?

**Comment by notrab** [comment]
Hey @spences10 

I am thinking that there could be an `examples` folder in the root directory, and each of the examples cover installing the `CartProvider`, as well as providing some basic functionality like https://github.com/notrab/react-use-cart#quick-start

What do you think?

**Comment by spences10** [comment]
Created #52 for consideration 🙏
