### ISSUE TITLE
Add Create React App example

### ISSUE THREAD

**Issue by notrab** [notrab/react-use-cart#35]
Using Create React App, we should add a basic demo showing how to wrap the global `CartProvider` and make similar function calls to those in #33 #34

**Comment by vmcodes** [comment]
Hi @notrab, I saw this as a good first issue. What are you looking for in an example in comparison to the demo and would you ideally be avoiding React UI frameworks?

**Comment by notrab** [comment]
@vmcodes it might be worth looking at https://github.com/notrab/react-use-cart/issues/34 and the associated PR by @spences10 to replicate something similar for CRA.

I'd probably avoid all styling as well, and just keep it super vanilla.
