### ISSUE TITLE
Improved CI process

### ISSUE THREAD

**Issue by ynnoj** [notrab/react-use-cart#63]
Appears that `yarn test` is only ran as part of the release workflow against the default branches (`main`, `beta`).

We should introduce CI for all PRs to ensure:

* The package builds.
* Tests pass.

We can use [`on.pull_request`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) with a separate workflow file to build and test the package.

**Comment by ynnoj** [comment]
@notrab Are you happy for me to draft a PR for this?

**Comment by notrab** [comment]
@ynnoj yep! PR and merge at will.

Here's what I had previously https://github.com/notrab/react-use-cart/pull/56/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88 which (could be improved?) and it was mistakenly removed 🙈
