### ISSUE TITLE
Missing type for updateCartMetadata [and others (?)]

### ISSUE THREAD

**Issue by KrallXZ** [notrab/react-use-cart#77]
Hey, the package's types definitions have some missing types.

`Property 'updateCartMetadata' does not exist on type 'CartProviderState'.`

CartProviderState:
```ts
export declare const CartProvider: React.FC<{
    children?: React.ReactNode;
    id?: string;
    defaultItems?: Item[];
    onSetItems?: (items: Item[]) => void;
    onItemAdd?: (payload: Item) => void;
    onItemUpdate?: (payload: object) => void;
    onItemRemove?: (id: Item["id"]) => void;
    storage?: (key: string, initialValue: string) => [string, (value: Function | string) => void];
    metadata?: Metadata;
}>;
```

**Comment by notrab** [comment]
Hey @KrallXZ 

This should be fixed in #75

I'll create a separate PR before though so this can get in now.

**Comment by notrab** [comment]
Fixed, not yet released. Will be bundled into a fix release over the next few days.

**Comment by salomaos** [comment]
Hi, any news on this!?

**Comment by notrab** [comment]
@salomaos if you install from GitHub in the meantime - you should see the type for this added. It'll be bundled into the next release that goes out.
