### ISSUE TITLE
Making multiple carts in one web app

### ISSUE THREAD

**Issue by Palmlight** [notrab/react-use-cart#81]
Please I would like to know if there's a way to make multiple carts. Where one can be for an admin and the other for customers

**Comment by notrab** [comment]
@Palmlight absolutely - if you see the demo [here](https://codesandbox.io/s/react-use-cart-3c7vm) you can provide an `id` to the `CartProvider` to achieve this 😄

**Comment by Palmlight** [comment]
Thank you so much🙌🏽🙌🏽🙌🏽🙌🏽🙌🏽🙌🏽

**Comment by muhaimincs** [comment]
Is there any api to show all of cart provider content? Thanks

**Comment by darrylmorley** [comment]
How do you add items to a specific cart ID? there doesn't;t seem to be anything in the example.

**Comment by notrab** [comment]
@darrylmorley that's a good point actually, it would require some changes to do provider to support multiple carts as the current implementation would only ever use the context of the current cart (even with unique ID).

I'm rebuilding cartql.com if you're looking for an API solution to better handle this kind of thing with a validation API (price/quantities) and webhooks.
