### ISSUE TITLE
Sync the cart's items between tabs

### ISSUE THREAD

**Issue by mattjis** [notrab/react-use-cart#97]
If a customer opens multiple tabs, I want them to be able to seamlessly transition between them and the cart to always show the actual items. At the moment a refresh is required which isn't optimal for the user experience.

**Comment by mattjis** [comment]
I achieved this by doing the following:

```javascript
import useWindowFocus from "use-window-focus"
import useLocalStorage from "use-local-storage"
```
```javascript
const windowFocused = useWindowFocus()
const [cartStorage] = useLocalStorage("react-use-cart", null)

useEffect(() => {
  if (!windowFocused) setItems(cartStorage.items)
}, [cartStorage])
```

**Comment by notrab** [comment]
Nice!

Perhaps we could add this to the library?

**Comment by mattjis** [comment]
@notrab Yeah sure, I think that would be a great idea.

I updated it to work a bit nicer with Next.js

**Comment by notrab** [comment]
@mattjis is this something you'd like to create a PR for?
